interface ICurrency {
  id: string;
}

export const AVAILABLE_CURRENCIES: ICurrency[] = [
  { id: "ARS" },
  { id: "AUD" },
  { id: "BGN" },
  { id: "DZD" },
  { id: "BRL" },
  { id: "CAD" },
  { id: "CHF" },
  { id: "CNY" },
  { id: "CZK" },
  { id: "DKK" },
  { id: "EUR" },
  { id: "GBP" },
  { id: "HKD" },
  { id: "HRK" },
  { id: "HUF" },
  { id: "IDR" },
  { id: "ILS" },
  { id: "INR" },
  { id: "ISK" },
  { id: "JPY" },
  { id: "KRW" },
  { id: "MAD" },
  { id: "MXN" },
  { id: "MYR" },
  { id: "NOK" },
  { id: "NZD" },
  { id: "PHP" },
  { id: "PLN" },
  { id: "RON" },
  { id: "RUB" },
  { id: "SEK" },
  { id: "SGD" },
  { id: "THB" },
  { id: "TRY" },
  { id: "TWD" },
  { id: "ZAR" },
];
